### ISSUE TITLE
Won't fix swatch order on category page?

### ISSUE THREAD

**Issue by mmodler** [robbieaverill/magento-attribute-option-order-fix#12]
Hi,

first, thanks for this bugfix module which works great on product detail page!

But it seems it doesn't fix swatch order on category page, the little swatches bottom of the product titles?

**Comment by robbieaverill** [comment]
Hey @mmodler

Thanks for reporting. I'll need to investigate- I had a feeling there could
be a conflict with swatches.

Will let you know.

Thanks
Robbie

**Comment by robbieaverill** [comment]
Hi @mmodler 

Please evaluate the code in the pull request and let me know.

Thanks
Robbie

**Comment by mmodler** [comment]
Hi Robbie,

i'll try on monday, thank you!

**Comment by mmodler** [comment]
Hi Robbie,

v1.1.1 with #12 breaks category view and search result page on my testshop:

```
a:5:{i:0;s:368:"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) ORDER BY `sort_order` ASC' at line 1, query was: SELECT `e`.`option_id`, `e`.`sort_order` FROM `eav_attribute_option` AS `e` WHERE (option_id IN ()) ORDER BY `sort_order` ASC";i:1;s:7290:"#0 /path_to_shop/public/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /path_to_shop/public/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /path_to_shop/public/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /path_to_shop/public/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `e`.`opt...', Array)
#4 /path_to_shop/public/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `e`.`opt...', Array)
#5 /path_to_shop/public/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /path_to_shop/src/robbieaverill_magento-attribute-option-order-fix/app/code/local/RobbieAverill/AttributeFix/Helper/Data.php(46): Zend_Db_Adapter_Abstract->fetchAll(Object(Varien_Db_Select))
#7 /path_to_shop/src/robbieaverill_magento-attribute-option-order-fix/app/code/local/RobbieAverill/AttributeFix/Helper/Data.php(19): RobbieAverill_AttributeFix_Helper_Data->getSortOrderForAttributeOptions(Array)
#8 /path_to_shop/src/robbieaverill_magento-attribute-option-order-fix/app/code/local/RobbieAverill/AttributeFix/Helper/Mediafallback.php(104): RobbieAverill_AttributeFix_Helper_Data->sortOptionValues(Array)
#9 /path_to_shop/public/app/code/core/Mage/ConfigurableSwatches/Model/Observer.php(56): RobbieAverill_AttributeFix_Helper_Mediafallback->attachConfigurableProductChildrenAttributeMapping(Array, 1)
#10 /path_to_shop/public/app/code/core/Mage/Core/Model/App.php(1357): Mage_ConfigurableSwatches_Model_Observer->productListCollectionLoadAfter(Object(Varien_Event_Observer))
#11 /path_to_shop/public/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(Mage_ConfigurableSwatches_Model_Observer), 'productListColl...', Object(Varien_Event_Observer))
#12 /path_to_shop/public/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_block_p...', Array)
#13 /path_to_shop/public/app/code/core/Mage/Catalog/Block/Product/List.php(164): Mage::dispatchEvent('catalog_block_p...', Array)
#14 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Catalog_Block_Product_List->_beforeToHtml()
#15 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#16 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('search_result_l...', true)
#17 /path_to_shop/public/app/code/core/Mage/CatalogSearch/Block/Result.php(161): Mage_Core_Block_Abstract->getChildHtml('search_result_l...')
#18 /path_to_shop/public/app/design/frontend/rwd/default/template/catalogsearch/result.phtml(42): Mage_CatalogSearch_Block_Result->getProductListHtml()
#19 /path_to_shop/public/app/code/core/Mage/Core/Block/Template.php(241): include('/kunden/128661_...')
#20 /path_to_shop/public/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#21 /path_to_shop/public/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#22 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#23 /path_to_shop/public/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#24 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#25 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#26 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#27 /path_to_shop/public/app/design/frontend/rwd/default/template/page/3columns.phtml(60): Mage_Core_Block_Abstract->getChildHtml('content')
#28 /path_to_shop/public/app/code/core/Mage/Core/Block/Template.php(241): include('/kunden/128661_...')
#29 /path_to_shop/public/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
#30 /path_to_shop/public/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#31 /path_to_shop/public/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#32 /path_to_shop/public/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#33 /path_to_shop/public/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#34 /path_to_shop/public/app/code/core/Mage/CatalogSearch/controllers/ResultController.php(80): Mage_Core_Controller_Varien_Action->renderLayout()
#35 /path_to_shop/public/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_CatalogSearch_ResultController->indexAction()
#36 /path_to_shop/public/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#37 /path_to_shop/public/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#38 /path_to_shop/public/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#39 /path_to_shop/public/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#40 /path_to_shop/public/de/index.php(87): Mage::run('test_de', 'store')
#41 {main}";s:3:"url";s:33:"/de/catalogsearch/result/?q=frohe";s:11:"script_name";s:13:"/de/index.php";s:4:"skin";s:15:"test_de";}
```

**Comment by robbieaverill** [comment]
Bugger. I will hot fix this in the morning.

**Comment by mmodler** [comment]
Thanks, i reverted #12 for now.

**Comment by robbieaverill** [comment]
Hi @mmodler 

I've deployed a hotfix for this scenario.

Thanks,
Robbie

**Comment by mmodler** [comment]
Hi @robbieaverill 

good news: search an category are no longer broken. bad news: swatch sorting on category not working again...

![unbenannt](https://cloud.githubusercontent.com/assets/1906217/12412034/e0ca11b0-be83-11e5-95d1-9193e04069a6.PNG)

**Comment by robbieaverill** [comment]
Hey @mmodler

Damn. What's the sort order defined for the swatch options?

Thanks,
Robbie

**Comment by robbieaverill** [comment]
Hey @mmodler

Damn. What's the sort order defined for the swatch options?

Thanks,
Robbie

On Tue, Jan 19, 2016 at 8:09 PM, mmodler <notifications@github.com> wrote:

> Hi @robbieaverill <https://github.com/robbieaverill>
>
> good news: search an category are no longer broken. bad news: swatch
> sorting on category not working again...
>
> [image: unbenannt]
> <https://cloud.githubusercontent.com/assets/1906217/12412034/e0ca11b0-be83-11e5-95d1-9193e04069a6.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robbieaverill/magento-attribute-option-order-fix/issues/12#issuecomment-172760618>
> .
>



-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by mmodler** [comment]
Hey @robbieaverill 

Sort looks fine for me:

![unbenannt](https://cloud.githubusercontent.com/assets/1906217/12412172/0de2d08c-be85-11e5-944c-269594baee00.PNG)

I think caregory sort order was correct with v1.1.1!

**Comment by robbieaverill** [comment]
@mmodler odd. I do not experience losing the swatch ordering using 1.1.2. Could you try clearing your cache etc, perhaps reindexing, then try again?

For reference, the only thing that I changed in 1.1.2 was adding handling for the edge case where an attribute has no options - this was what was causing the SQL state violation in your stack trace. The method in question is unit tested both ways now and the result for case where the attribute _does_ have options hasn't changed between 1.1.1 and 1.1.2.

Hope this helps.
Robbie

**Comment by robbieaverill** [comment]
Hi @mmodler 

Would you mind checking the latest version of this repo to confirm you're still experiencing the issue?

Thanks,
Robbie

**Comment by mmodler** [comment]
I tried 1.1.4 with latest magento 1.9.x and everything seems to be fine. Thanks!
